In [3]:
import torch
import numpy as np

In [4]:
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [5]:
import torch.utils.data as Data

batch_size = 10
# 将训练数据的特征和标签组合
dataset = Data.TensorDataset(features, labels)
# 随机读取⼩批量
data_iter = Data.DataLoader(dataset, batch_size, shuffle=True)

In [6]:
for X, y in data_iter:
    print(X, y)
    break

tensor([[-0.1180,  0.5752],
        [ 1.4879, -0.2938],
        [-1.6221, -0.2645],
        [-1.9013,  0.4345],
        [-0.2202, -0.1198],
        [ 0.5458, -0.9779],
        [ 0.4022,  1.4735],
        [-0.3682,  0.9713],
        [ 0.3857,  0.5686],
        [ 1.5530, -0.4803]]) tensor([ 2.0047,  8.1753,  1.8587, -1.0799,  4.1648,  8.5997, -0.0153,  0.1628,
         3.0371,  8.9453])


In [8]:
import torch.nn as nn

class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)
    # forward 定义前向传播
    def forward(self, x):
        y = self.linear(x)
        return y

net = LinearNet(num_inputs)
print(net) # 使⽤print可以打印出⽹络的结构

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [10]:
# 写法⼀
net = nn.Sequential(
    nn.Linear(num_inputs, 1)
    # 此处还可以传⼊其他层
)

# 写法⼆
net = nn.Sequential()
net.add_module('linear', nn.Linear(num_inputs, 1))
# net.add_module ......

# 写法三
from collections import OrderedDict
net = nn.Sequential(OrderedDict([
    ('linear', nn.Linear(num_inputs, 1))
]))

print(net)
print(net[0])

Sequential(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [11]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.3264,  0.2954]], requires_grad=True)
Parameter containing:
tensor([-0.4950], requires_grad=True)


In [ ]:
from torch.nn import init

init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0) # 也可以直接修改bias的data:net[0].bias.data.fill_(0)