In [42]:
import torch

In [43]:
x = torch.empty(5, 3)
print(x)

tensor([[-1.0091e+31,  4.5877e-41,  3.6061e-36],
        [ 0.0000e+00,         nan,  0.0000e+00],
        [ 4.4653e+30,  1.3428e+13,  9.5870e+26],
        [ 4.1984e+12,  9.3157e-39,  0.0000e+00],
        [ 8.9683e-44,  0.0000e+00,  8.9683e-44]])


In [44]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4594, 0.7552, 0.0347],
        [0.8694, 0.1831, 0.8495],
        [0.9725, 0.2148, 0.8892],
        [0.7496, 0.4507, 0.0535],
        [0.3259, 0.4130, 0.8534]])


In [45]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [46]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [47]:
x = x.new_ones(5, 3, dtype=torch.float64)  # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x, dtype=torch.float) # 指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.5042, -0.9491, -0.0941],
        [ 0.8977, -0.7007, -0.3743],
        [-0.1428, -0.4805, -0.8053],
        [-0.6811, -0.4652, -0.6431],
        [-0.8272, -1.5029, -1.6878]])


In [48]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [49]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.2190,  0.0466,  0.4386],
        [ 0.9927, -0.0106,  0.5435],
        [ 0.6661, -0.2024, -0.5174],
        [-0.5372, -0.1886,  0.2332],
        [-0.2020, -0.8173, -0.9338]])


In [50]:
print(torch.add(x, y))

tensor([[-0.2190,  0.0466,  0.4386],
        [ 0.9927, -0.0106,  0.5435],
        [ 0.6661, -0.2024, -0.5174],
        [-0.5372, -0.1886,  0.2332],
        [-0.2020, -0.8173, -0.9338]])


In [51]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.2190,  0.0466,  0.4386],
        [ 0.9927, -0.0106,  0.5435],
        [ 0.6661, -0.2024, -0.5174],
        [-0.5372, -0.1886,  0.2332],
        [-0.2020, -0.8173, -0.9338]])


In [52]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.2190,  0.0466,  0.4386],
        [ 0.9927, -0.0106,  0.5435],
        [ 0.6661, -0.2024, -0.5174],
        [-0.5372, -0.1886,  0.2332],
        [-0.2020, -0.8173, -0.9338]])


In [53]:
y = x[0, :]
y += 1
print(y)
print(x[0, :]) # 源tensor也被改了

tensor([0.4958, 0.0509, 0.9059])
tensor([0.4958, 0.0509, 0.9059])


In [54]:
y = x.view(15)
z = x.view(-1, 5) # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([5, 3]) torch.Size([15]) torch.Size([3, 5])


In [55]:
x += 1
print(x)
print(y)

tensor([[ 1.4958,  1.0509,  1.9059],
        [ 1.8977,  0.2993,  0.6257],
        [ 0.8572,  0.5195,  0.1947],
        [ 0.3189,  0.5348,  0.3569],
        [ 0.1728, -0.5029, -0.6878]])
tensor([ 1.4958,  1.0509,  1.9059,  1.8977,  0.2993,  0.6257,  0.8572,  0.5195,
         0.1947,  0.3189,  0.5348,  0.3569,  0.1728, -0.5029, -0.6878])


In [56]:
x_cp = x.clone().view(15)
x -= 1
print(x)
print(x_cp)

tensor([[ 0.4958,  0.0509,  0.9059],
        [ 0.8977, -0.7007, -0.3743],
        [-0.1428, -0.4805, -0.8053],
        [-0.6811, -0.4652, -0.6431],
        [-0.8272, -1.5029, -1.6878]])
tensor([ 1.4958,  1.0509,  1.9059,  1.8977,  0.2993,  0.6257,  0.8572,  0.5195,
         0.1947,  0.3189,  0.5348,  0.3569,  0.1728, -0.5029, -0.6878])


In [57]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.3839])
-1.383904218673706


In [58]:
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)

tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [59]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = y + x
print(id(y) == id_before)

False


In [60]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = y + x
print(id(y) == id_before)

True


In [61]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y) # y += x, y.add_(x)
print(id(y) == id_before)

True


In [62]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [63]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [64]:
c = torch.tensor(a)
a += 1
print(a, c)

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [65]:
 # 以下代码只有在PyTorch GPU版本上才会执⾏
 if torch.cuda.is_available():
     device = torch.device("cuda")             # GPU
     y = torch.ones_like(x, device=device)     # 直接创建⼀个在GPU上的Tensor
     x = x.to(device)                          # 等价于 .to("cuda")
     z = x + y
     print(z)
     print(z.to("cpu", torch.double))          # to()还可以同时更改数据类型

In [66]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [67]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [68]:
print(x.is_leaf, y.is_leaf)

True False


In [69]:
z = y * y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [70]:
a = torch.randn(2, 2) # 缺失情况下默认 requires_grad = False
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad) # True
b = (a * a).sum()
print(b.grad_fn)

False
True


In [71]:
out.backward() # 等价于 out.backward(torch.tensor(1.))

In [72]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [73]:
# 再来反向传播⼀次，注意grad是累加的
out2 = x.sum()
out2.backward()
print(x.grad)

out3 = x.sum()
x.grad.data.zero_()
out3.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])
tensor([[1., 1.],
        [1., 1.]])


In [74]:
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x
z = y.view(2, 2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward0>)


In [75]:
v = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.2000, 0.0200, 0.0020])


In [76]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2

print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [77]:
y3.backward()
print(x.grad)

tensor(2.)


In [78]:
x = torch.ones(1, requires_grad=True)

print(x.data) # 还是⼀个tensor
print(x.data.requires_grad)  # 但是已经是独⽴于计算图之外

y = 2 * x
x.data *= 100 # 只改变了值，不会记录在计算图，所以不会影响梯度传播

y.backward()
print(x)  # 更改data的值也会影响tensor的值
print(x.grad)

tensor([1.])
False
tensor([100.], requires_grad=True)
tensor([2.])
